module.exports = {
  apps: [
    {
      name: "flint-bot",
      script: "start-bot.js",
      args: "flint",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/flint-err.log",
      out_file: "./logs/flint-out.log",
      log_file: "./logs/flint-combined.log",
      time: true,
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: "koko-bot",
      script: "start-bot.js",
      args: "koko",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/koko-err.log",
      out_file: "./logs/koko-out.log",
      log_file: "./logs/koko-combined.log",
      time: true,
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: "robin-bot",
      script: "start-bot.js",
      args: "robin",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/robin-err.log",
      out_file: "./logs/robin-out.log",
      log_file: "./logs/robin-combined.log",
      time: true,
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
};
